apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow-worker
  template:
    metadata:
      labels:
        app: airflow-worker
    spec:
      containers:
        - name: airflow-worker
          image: apache/airflow:latest
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "CeleryExecutor"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow"
            - name: AIRFLOW__CELERY__BROKER_URL
              value: "redis://redis:6379/0"
            - name: AIRFLOW__CELERY__RESULT_BACKEND
              value: "db+postgresql://airflow:airflow@postgres-airflow:5432/airflow"
          command: ["bash", "-c"]
          args:
            - |
              exec airflow celery worker
